// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoPasteCurrentItem() {
  return window['go']['main']['App']['AutoPasteCurrentItem']();
}

export function ClearAllItems() {
  return window['go']['main']['App']['ClearAllItems']();
}

export function ClearItemsOlderThanDays(arg1) {
  return window['go']['main']['App']['ClearItemsOlderThanDays'](arg1);
}

export function CollectCurrentItem() {
  return window['go']['main']['App']['CollectCurrentItem']();
}

export function CopyCurrentItem() {
  return window['go']['main']['App']['CopyCurrentItem']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function CopyTextToClipboard(arg1) {
  return window['go']['main']['App']['CopyTextToClipboard'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function DeleteCurrentItem() {
  return window['go']['main']['App']['DeleteCurrentItem']();
}

export function DeleteUserScript(arg1) {
  return window['go']['main']['App']['DeleteUserScript'](arg1);
}

export function DetectQRCode(arg1) {
  return window['go']['main']['App']['DetectQRCode'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateQRCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateQRCode'](arg1, arg2);
}

export function GetAllUserScripts() {
  return window['go']['main']['App']['GetAllUserScripts']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetClipboardItemByID(arg1) {
  return window['go']['main']['App']['GetClipboardItemByID'](arg1);
}

export function GetClipboardItems(arg1) {
  return window['go']['main']['App']['GetClipboardItems'](arg1);
}

export function GetCurrentLanguage() {
  return window['go']['main']['App']['GetCurrentLanguage']();
}

export function GetEnabledUserScriptsByTrigger(arg1) {
  return window['go']['main']['App']['GetEnabledUserScriptsByTrigger'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetSupportedLanguages() {
  return window['go']['main']['App']['GetSupportedLanguages']();
}

export function GetUserScriptByID(arg1) {
  return window['go']['main']['App']['GetUserScriptByID'](arg1);
}

export function GetUserScriptsByIDs(arg1) {
  return window['go']['main']['App']['GetUserScriptsByIDs'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function HideWindowAndQuit() {
  return window['go']['main']['App']['HideWindowAndQuit']();
}

export function HttpRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HttpRequest'](arg1, arg2, arg3, arg4);
}

export function NextItem() {
  return window['go']['main']['App']['NextItem']();
}

export function OpenFileInFinder(arg1) {
  return window['go']['main']['App']['OpenFileInFinder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PrevItem() {
  return window['go']['main']['App']['PrevItem']();
}

export function RecognizeQRCode(arg1) {
  return window['go']['main']['App']['RecognizeQRCode'](arg1);
}

export function RestartRegisterHotkey() {
  return window['go']['main']['App']['RestartRegisterHotkey']();
}

export function RunScript() {
  return window['go']['main']['App']['RunScript']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveImagePNG(arg1, arg2) {
  return window['go']['main']['App']['SaveImagePNG'](arg1, arg2);
}

export function SaveUserScript(arg1) {
  return window['go']['main']['App']['SaveUserScript'](arg1);
}

export function SearchClipboardItems(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1, arg2, arg3, arg4);
}

export function SearchItem() {
  return window['go']['main']['App']['SearchItem']();
}

export function SetDockIconVisibility(arg1) {
  return window['go']['main']['App']['SetDockIconVisibility'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function ShowSetting() {
  return window['go']['main']['App']['ShowSetting']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SwitchLeftTab(arg1) {
  return window['go']['main']['App']['SwitchLeftTab'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TranslateCurrentItem() {
  return window['go']['main']['App']['TranslateCurrentItem']();
}

export function UpdateUserScriptOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserScriptOrder'](arg1, arg2);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
