// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function AutoPasteCurrentItem():Promise<void>;

export function ClearAllItems():Promise<void>;

export function ClearItemsOlderThanDays(arg1:number):Promise<void>;

export function CollectCurrentItem():Promise<void>;

export function CopyCurrentItem():Promise<void>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function CopyTextToClipboard(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function DeleteCurrentItem():Promise<void>;

export function DeleteUserScript(arg1:string):Promise<void>;

export function DetectQRCode(arg1:string):Promise<boolean>;

export function ForceQuit():Promise<void>;

export function GenerateQRCode(arg1:string,arg2:number):Promise<string>;

export function GetAllUserScripts():Promise<Array<common.UserScript>>;

export function GetAppSettings():Promise<string>;

export function GetClipboardItemByID(arg1:string):Promise<common.ClipboardItem>;

export function GetClipboardItems(arg1:number):Promise<Array<common.ClipboardItem>>;

export function GetCurrentLanguage():Promise<string>;

export function GetEnabledUserScriptsByTrigger(arg1:string):Promise<Array<common.UserScript>>;

export function GetFileInfo(arg1:string):Promise<Array<common.FileInfo>>;

export function GetStatistics():Promise<Record<string, any>>;

export function GetSupportedLanguages():Promise<Array<string>>;

export function GetUserScriptByID(arg1:string):Promise<common.UserScript>;

export function HideWindow():Promise<void>;

export function HideWindowAndQuit():Promise<void>;

export function HttpRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function NextItem():Promise<void>;

export function OpenFileInFinder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PrevItem():Promise<void>;

export function RecognizeQRCode(arg1:string):Promise<string>;

export function RestartRegisterHotkey():Promise<void>;

export function RunScript():Promise<void>;

export function SaveAppSettings(arg1:string):Promise<void>;

export function SaveImagePNG(arg1:string,arg2:string):Promise<string>;

export function SaveUserScript(arg1:string):Promise<void>;

export function SearchClipboardItems(arg1:boolean,arg2:string,arg3:string,arg4:number):Promise<Array<common.ClipboardItem>>;

export function SearchItem():Promise<void>;

export function SetDockIconVisibility(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShowAbout():Promise<void>;

export function ShowSetting():Promise<void>;

export function ShowWindow():Promise<void>;

export function SwitchLeftTab(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<number>;

export function TranslateCurrentItem():Promise<void>;

export function UpdateUserScriptOrder(arg1:string,arg2:number):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
