// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function ClearAllItems():Promise<void>;

export function ClearItemsOlderThanDays(arg1:number):Promise<void>;

export function ClearOldItems(arg1:number):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function GetAppSettings():Promise<string>;

export function GetClipboardItemByID(arg1:string):Promise<common.ClipboardItem>;

export function GetClipboardItems(arg1:number):Promise<Array<common.ClipboardItem>>;

export function GetFileInfo(arg1:string):Promise<Array<common.FileInfo>>;

export function GetStatistics():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function OpenFileInFinder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:string):Promise<void>;

export function SaveImagePNG(arg1:string,arg2:string):Promise<string>;

export function SearchClipboardItems(arg1:string,arg2:string,arg3:number):Promise<Array<common.ClipboardItem>>;

export function ShowWindow():Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
