// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllItems() {
  return window['go']['main']['App']['ClearAllItems']();
}

export function ClearItemsOlderThanDays(arg1) {
  return window['go']['main']['App']['ClearItemsOlderThanDays'](arg1);
}

export function ClearOldItems(arg1) {
  return window['go']['main']['App']['ClearOldItems'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetClipboardItemByID(arg1) {
  return window['go']['main']['App']['GetClipboardItemByID'](arg1);
}

export function GetClipboardItems(arg1) {
  return window['go']['main']['App']['GetClipboardItems'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenFileInFinder(arg1) {
  return window['go']['main']['App']['OpenFileInFinder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveImagePNG(arg1, arg2) {
  return window['go']['main']['App']['SaveImagePNG'](arg1, arg2);
}

export function SearchClipboardItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1, arg2, arg3);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
