name: Build & Release (Go/Wails)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: "1"
      MACOSX_DEPLOYMENT_TARGET: "11.0"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-amd64
            platform: linux/amd64
            archive: clip-save-linux-amd64-${{ github.ref_name }}.zip
          - os: windows-latest
            name: windows-amd64
            platform: windows/amd64
            archive: clip-save-windows-amd64-${{ github.ref_name }}.zip
          - os: macos-latest
            name: macos-arm64
            platform: darwin/arm64
            archive: clip-save-macos-arm64-${{ github.ref_name }}.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go (from go.mod)
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            frontend/package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # --- OS specific prerequisites ---
      - name: Install Linux deps (GTK/WebKit/CGo)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install Windows deps (mingw)
        if: runner.os == 'Windows'
        run: |
          choco install -y mingw

      - name: Setup macOS build environment
        if: runner.os == 'macOS'
        run: |
          # 检查当前状态
          echo "Current xcode-select path:"
          xcode-select -p || echo "No xcode-select path set"
          
          # 设置 Command Line Tools 路径
          sudo xcode-select -switch /Library/Developer/CommandLineTools
          
          # 查找 macOS SDK
          echo "Looking for macOS SDK:"
          SDK_PATH=$(xcrun --show-sdk-path 2>/dev/null || echo "")
          if [ -z "$SDK_PATH" ]; then
            echo "No SDK found via xcrun, trying manual search..."
            SDK_PATH=$(find /Library/Developer/CommandLineTools/SDKs -name "MacOSX.sdk" -type d 2>/dev/null | head -1)
          fi
          
          echo "SDK Path: $SDK_PATH"
          
          # 验证 SDK 存在并包含必要头文件
          if [ -d "$SDK_PATH" ] && [ -f "$SDK_PATH/usr/include/stdlib.h" ]; then
            echo "SDK found and contains stdlib.h"
            echo "SDKROOT=$SDK_PATH" >> $GITHUB_ENV
          else
            echo "SDK not found or incomplete, installing Command Line Tools..."
            sudo xcode-select --install
            sleep 30
            sudo xcode-select -switch /Library/Developer/CommandLineTools
            SDK_PATH=$(xcrun --show-sdk-path)
            echo "SDKROOT=$SDK_PATH" >> $GITHUB_ENV
          fi
          
          # 设置编译器路径和标志
          echo "CC=/Library/Developer/CommandLineTools/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/Library/Developer/CommandLineTools/usr/bin/clang++" >> $GITHUB_ENV
          echo "PATH=/Library/Developer/CommandLineTools/usr/bin:$PATH" >> $GITHUB_ENV
          
          # 设置 CGO 标志
          echo "CGO_CFLAGS=-isysroot $SDK_PATH" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-isysroot $SDK_PATH" >> $GITHUB_ENV
          
          # 最终验证
          echo "Final environment:"
          echo "CC: /Library/Developer/CommandLineTools/usr/bin/clang"
          echo "SDKROOT: $SDK_PATH"
          echo "CGO_CFLAGS: -isysroot $SDK_PATH"
          echo "CGO_LDFLAGS: -isysroot $SDK_PATH"
          
          # 测试编译器
          /Library/Developer/CommandLineTools/usr/bin/clang --version
          echo "xcode-select path:"
          xcode-select -p

      # --- Build steps ---
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Go deps
        run: go mod tidy

      - name: Frontend deps
        run: |
          cd frontend
          npm ci

      - name: Build (wails)
        env:
          CGO_ENABLED: "1"
          GOBIN: ${{ github.workspace }}/bin
          PATH: ${{ github.workspace }}/bin:${{ env.PATH }}
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}
          SDKROOT: ${{ env.SDKROOT }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
        run: |
          echo "Build environment:"
          echo "CC: $CC"
          echo "CXX: $CXX"
          echo "SDKROOT: $SDKROOT"
          echo "CGO_CFLAGS: $CGO_CFLAGS"
          echo "CGO_LDFLAGS: $CGO_LDFLAGS"
          echo "CGO_ENABLED: $CGO_ENABLED"
          echo "PATH: $PATH"
          wails build -platform ${{ matrix.platform }}

      # --- Archive artifacts per OS ---
      - name: Pack artifact (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          zip -r "../${{ matrix.archive }}" ./bin
          cd ..
      - name: Pack artifact (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path build\bin\* -DestinationPath "${{ matrix.archive }}"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.archive }}
          if-no-files-found: error

  release:
    name: Create/Update Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded files
        run: ls -R dist

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
